#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-tracker-soname2.0
Version  : 2.3.6
Release  : 2
URL      : https://download.gnome.org/sources/tracker/2.3/tracker-2.3.6.tar.xz
Source0  : https://download.gnome.org/sources/tracker/2.3/tracker-2.3.6.tar.xz
Summary  : Tracker : A library to perform SPARQL queries and updates in the \
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 LGPL-2.1
Requires: compat-tracker-soname2.0-lib = %{version}-%{release}
Requires: compat-tracker-soname2.0-license = %{version}-%{release}
Requires: compat-tracker-soname2.0-locales = %{version}-%{release}
BuildRequires : bash-completion-dev
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gobject-introspection-dev
BuildRequires : gstreamer-dev
BuildRequires : json-glib-dev
BuildRequires : libexif-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libsoup-dev
BuildRequires : libunistring-dev
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(libnm)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(zlib)
BuildRequires : systemd-dev

%description
The turtle files are created in this directory. For importing them into
tracker use:

%package lib
Summary: lib components for the compat-tracker-soname2.0 package.
Group: Libraries
Requires: compat-tracker-soname2.0-license = %{version}-%{release}

%description lib
lib components for the compat-tracker-soname2.0 package.


%package license
Summary: license components for the compat-tracker-soname2.0 package.
Group: Default

%description license
license components for the compat-tracker-soname2.0 package.


%package locales
Summary: locales components for the compat-tracker-soname2.0 package.
Group: Default

%description locales
locales components for the compat-tracker-soname2.0 package.


%prep
%setup -q -n tracker-2.3.6
cd %{_builddir}/tracker-2.3.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600364177
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dfts=false \
-Dfunctional_tests=false \
-Dman=false \
-Ddocs=false  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/compat-tracker-soname2.0
cp %{_builddir}/tracker-2.3.6/COPYING.GPL %{buildroot}/usr/share/package-licenses/compat-tracker-soname2.0/33fabce185708a9b17df7a9f37c7ed44eddc7e48
cp %{_builddir}/tracker-2.3.6/COPYING.LGPL %{buildroot}/usr/share/package-licenses/compat-tracker-soname2.0/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/tracker-2.3.6/src/libtracker-common/COPYING.LIB %{buildroot}/usr/share/package-licenses/compat-tracker-soname2.0/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/tracker-2.3.6/src/libtracker-data/COPYING.LIB %{buildroot}/usr/share/package-licenses/compat-tracker-soname2.0/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/tracker-2.3.6/src/libtracker-miner/COPYING.LIB %{buildroot}/usr/share/package-licenses/compat-tracker-soname2.0/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/tracker-2.3.6/utils/ontology/resources/LICENSE.txt %{buildroot}/usr/share/package-licenses/compat-tracker-soname2.0/2a048acc60f0c772323612a467cdfb0718c1ba0e
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang tracker
## Remove excluded files
rm -f %{buildroot}/usr/bin/tracker
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-control/tracker-control.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-control/tracker-miner-manager.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-miner/tracker-data-provider.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-miner/tracker-decorator-fs.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-miner/tracker-decorator.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-miner/tracker-indexing-tree.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-miner/tracker-miner-enum-types.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-miner/tracker-miner-enums.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-miner/tracker-miner-fs.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-miner/tracker-miner-object.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-miner/tracker-miner-online.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-miner/tracker-miner-proxy.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-miner/tracker-miner.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-sparql/tracker-generated.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-sparql/tracker-namespace-manager.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-sparql/tracker-notifier.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-sparql/tracker-ontologies.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-sparql/tracker-resource.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-sparql/tracker-sparql.h
rm -f %{buildroot}/usr/include/tracker-2.0/libtracker-sparql/tracker-version.h
rm -f %{buildroot}/usr/lib/systemd/user/tracker-store.service
rm -f %{buildroot}/usr/lib64/girepository-1.0/Tracker-2.0.typelib
rm -f %{buildroot}/usr/lib64/girepository-1.0/TrackerControl-2.0.typelib
rm -f %{buildroot}/usr/lib64/girepository-1.0/TrackerMiner-2.0.typelib
rm -f %{buildroot}/usr/lib64/libtracker-control-2.0.so
rm -f %{buildroot}/usr/lib64/libtracker-miner-2.0.so
rm -f %{buildroot}/usr/lib64/libtracker-sparql-2.0.so
rm -f %{buildroot}/usr/lib64/pkgconfig/tracker-control-2.0.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/tracker-miner-2.0.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/tracker-sparql-2.0.pc
rm -f %{buildroot}/usr/lib64/tracker-2.0/trackertestutils/__init__.py
rm -f %{buildroot}/usr/lib64/tracker-2.0/trackertestutils/dconf.py
rm -f %{buildroot}/usr/lib64/tracker-2.0/trackertestutils/helpers.py
rm -f %{buildroot}/usr/lib64/tracker-2.0/trackertestutils/mainloop.py
rm -f %{buildroot}/usr/libexec/tracker-store
rm -f %{buildroot}/usr/share/bash-completion/completions/tracker
rm -f %{buildroot}/usr/share/dbus-1/services/org.freedesktop.Tracker1.service
rm -f %{buildroot}/usr/share/gir-1.0/Tracker-2.0.gir
rm -f %{buildroot}/usr/share/gir-1.0/TrackerControl-2.0.gir
rm -f %{buildroot}/usr/share/gir-1.0/TrackerMiner-2.0.gir
rm -f %{buildroot}/usr/share/glib-2.0/schemas/org.freedesktop.Tracker.DB.gschema.xml
rm -f %{buildroot}/usr/share/glib-2.0/schemas/org.freedesktop.Tracker.FTS.gschema.xml
rm -f %{buildroot}/usr/share/glib-2.0/schemas/org.freedesktop.Tracker.Store.gschema.xml
rm -f %{buildroot}/usr/share/glib-2.0/schemas/org.freedesktop.Tracker.enums.xml
rm -f %{buildroot}/usr/share/glib-2.0/schemas/org.freedesktop.Tracker.gschema.xml
rm -f %{buildroot}/usr/share/tracker/domain-ontologies/default.rule
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/30-nie.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/30-nie.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/32-nco.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/32-nco.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/33-nfo.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/33-nfo.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/34-nmo.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/34-nmo.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/35-ncal.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/35-ncal.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/36-scal.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/36-scal.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/37-nid3.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/37-nid3.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/38-nmm.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/38-nmm.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/39-mto.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/39-mto.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/40-mlo.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/40-mlo.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/41-mfo.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/41-mfo.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/89-mtp.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/89-mtp.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/90-tracker.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/90-tracker.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/91-maemo.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/91-maemo.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/92-slo.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/92-slo.ontology
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/93-libosinfo.description
rm -f %{buildroot}/usr/share/tracker/ontologies/nepomuk/93-libosinfo.ontology
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.da
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.de
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.en
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.es
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.fi
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.fr
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.hu
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.it
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.nb
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.nl
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.pt
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.ru
rm -f %{buildroot}/usr/share/tracker/stop-words/stopwords.sv
rm -f %{buildroot}/usr/share/tracker/tracker-backup.xml
rm -f %{buildroot}/usr/share/tracker/tracker-miner.xml
rm -f %{buildroot}/usr/share/tracker/tracker-resources.xml
rm -f %{buildroot}/usr/share/tracker/tracker-statistics.xml
rm -f %{buildroot}/usr/share/tracker/tracker-status.xml
rm -f %{buildroot}/usr/share/vala/vapi/tracker-control-2.0.deps
rm -f %{buildroot}/usr/share/vala/vapi/tracker-control-2.0.vapi
rm -f %{buildroot}/usr/share/vala/vapi/tracker-miner-2.0.deps
rm -f %{buildroot}/usr/share/vala/vapi/tracker-miner-2.0.vapi
rm -f %{buildroot}/usr/share/vala/vapi/tracker-sparql-2.0.deps
rm -f %{buildroot}/usr/share/vala/vapi/tracker-sparql-2.0.vapi

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtracker-control-2.0.so.0
/usr/lib64/libtracker-control-2.0.so.0.306.0
/usr/lib64/libtracker-miner-2.0.so.0
/usr/lib64/libtracker-miner-2.0.so.0.306.0
/usr/lib64/libtracker-sparql-2.0.so.0
/usr/lib64/libtracker-sparql-2.0.so.0.306.0
/usr/lib64/tracker-2.0/libtracker-data.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-tracker-soname2.0/2a048acc60f0c772323612a467cdfb0718c1ba0e
/usr/share/package-licenses/compat-tracker-soname2.0/33fabce185708a9b17df7a9f37c7ed44eddc7e48
/usr/share/package-licenses/compat-tracker-soname2.0/9a1929f4700d2407c70b507b3b2aaf6226a9543c

%files locales -f tracker.lang
%defattr(-,root,root,-)

